#!/bin/bash
#SBATCH --job-name=ITS_analysis
#SBATCH --output=ITS_analysis_output.log
#SBATCH --error=ITS_analysis_error.log
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --time=72:00:00
#SBATCH --mem=100G

###########################################
# ITS Analysis Pipeline for OTU
###########################################
 conda activate qiime2-amplicon-2023.9
 
 
# Primers
# 5'-GAACCWGCGGARGGATCA-3'
# 5'-GCTGCGTTCTTCATCGATGC-3'

##### Import sequences with the manifest
qiime tools import \
  --type 'SampleData[PairedEndSequencesWithQuality]' \
  --input-path manifest.tsv \
  --output-path paired-end-demux.qza \
  --input-format PairedEndFastqManifestPhred33V2

# ITSXpress trimming
qiime itsxpress trim-pair-output-unmerged \
  --i-per-sample-sequences paired-end-demux.qza \
  --p-region ITS1 \
  --p-taxa F \
  --p-cluster-id 1.0 \
  --p-threads 28 \
  --o-trimmed trimmed_exact.qza

# Summarize demultiplexed sequences
qiime demux summarize \
  --i-data trimmed_exact.qza \
  --o-visualization reads_trimmed_summary.qzv
 


########VSEARCH

qiime vsearch cluster-features-de-novo --help

qiime vsearch cluster-features-de-novo \
  --i-table 04_denoise \
  --i-sequences 04_denoise/representative_sequences.qza \
  --p-perc-identity 0.97 \
  --output-dir 05_clustered

  
  #############EXPORT

# Ensure the output directory exists

qiime feature-classifier classify-sklearn \
  --i-classifier unite-ver9-classifier-23.qza \
  --i-reads 05_clustered/clustered_sequences.qza \
  --output-dir 05_taxonomy
 
  

# Phylogenetic analysis
qiime phylogeny align-to-tree-mafft-fasttree \
  --i-sequences 05_clustered/clustered_sequences.qza \
  --o-alignment aligned-rep-seqs.qza \
  --o-masked-alignment masked-aligned-rep-seqs.qza \
  --o-tree unrooted-tree.qza \
  --o-rooted-tree rooted-tree.qza


# Export tree
qiime tools export \
  --input-path rooted-tree.qza \
  --output-path exported_files


qiime taxa barplot \
 --i-table 05_clustered/clustered_table.qza \
 --i-taxonomy 05_taxonomy/classification.qza \
 --m-metadata-file metadata.txt \
 --o-visualization taxa-bar-plots.qzv

 
 
# Alpha rarefaction
qiime diversity alpha-rarefaction \
  --i-table 05_clustered/clustered_table.qza \
  --i-phylogeny rooted-tree.qza \
  --p-max-depth 20000 \
  --m-metadata-file metadata.txt \
  --o-visualization alpha-rarefaction.qzv



#!/bin/bash

# Modify taxonomy.tsv
sed 's/Feature ID/#OTUID/g' 05_taxonomy/export/taxonomy.tsv | sed 's/Taxon/taxonomy/g' | sed 's/Consensus/confidence/g' > 05_taxonomy/export/ref.taxonomy.tsv


# Add metadata to BIOM
biom add-metadata \
  -i 05_clustered/clustered_table.export/feature-table.biom \
  -o 05_clustered/clustered_table.export/taxonomy.feature-table.biom \
  --observation-metadata-fp 05_taxonomy/export/ref.taxonomy.tsv \
  --sc-separated taxonomy
  
  

# Convert to TSV format
biom convert -i 05_clustered/clustered_table.export/taxonomy.feature-table.biom -o 05_clustered/clustered_table.export/taxonomy.feature-table.tsv --to-tsv --header-key taxonomy

echo "Processing completed."


 

# Prepare taxonomy for BIOM
sed 's/Feature ID/#OTUID/g' "05_taxonomy/export/taxonomy.tsv" | \
sed 's/Taxon/taxonomy/g' | \
sed 's/Consensus/confidence/g' > "05_taxonomy/export/reformat.taxonomy.tsv"

# Add metadata to BIOM
biom add-metadata \
  -i "04_denoise/table.qza.export/feature-table.biom" \
  -o "04_denoise/table.qza.export/taxonomy.feature-table.biom" \
  --observation-metadata-fp "05_taxonomy/export/reformat.taxonomy.tsv" \
  --sc-separated taxonomy

# Convert BIOM to TSV
biom convert \
  -i "04_denoise/table.qza.export/taxonomy.feature-table.biom" \
  -o "04_denoise/table.qza.export/taxonomy.feature-table.biom" \
  --to-tsv \
  --header-key taxonomy

